name: Pull Request Action
permissions: write-all
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Install jq and yq
        run: |
          sudo apt-get -y install jq
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update Config Params and Create Pull Requests
        run: |
         urls=$(curl -sSL https://raw.githubusercontent.com/rndquu/bounty-bot/development/projects.json | jq -r '.urls[]')

          for url in $urls
          do
            repoName=$(basename $url)
            ownerName=$(echo $url | awk -F/ '{print $(NF-1)}')

            git clone $url $repoName
            cd $repoName

            defaultBranch=$(git branch --show-current)

            # make a branch to update config #
            git branch update
            git checkout update
